### ISSUE TITLE
1.15 Not Working

### ISSUE THREAD

**Issue by Jacohun1** [okx-code/Rankup3#28]
https://paste.ofcode.org/t9kFVrjnXQiAFnFMuQ7HXN

Wont let my players rankup in game after updating to 1.15

**Comment by okx-code** [comment]
This is an outdated version of rankup (but I doubt updating will fully solve the issue) . Your config is setup for a pre-flattening server. This line https://github.com/okx-code/Rankup3/blob/master/src/main/resources/config.yml#L57 in config.yml needs to be in https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html. (so try BLACK_STAINED_GLASS_PANE instead of STAINED_GLASS_PANE)

**Comment by okx-code** [comment]
I was mistaken earlier, I was wrong about what I said and updating does indeed solve the issue.
